name = "hono-cloudflare-workers"
main = "src/index.ts"
compatibility_date = "2024-12-22"
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_TYPE = "d1" # or "mongodb"

[[d1_databases]]
binding = "DB"
database_name = "sample-database"
database_id = "31651fbb-a8ab-427a-a127-103c3a98b96e"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1